Feature/error reporting+async
yOoZZyOzzbourne/mobile-assignment-Quanti pull request #4
Opened 2023-05-05 15:26 UTC by yOoZZyOzzbourne

2023-05-12 14:20 UTC, troupmar requested changes

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Features/Sources/RocketErrorView/RocketErrorView.swift
> +               fatalError()
Tak tohle se fakt nedela :D Za zadnou cenu nesmis pripustit aby appka spadla. A uz vubec to nesmis sam dirigovat...

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Features/Sources/RocketErrorView/RocketErrorView.swift
> +   public var body: some View {
Prijde mi, ze v tomhle souboru mas nejakej velkej indent. Pouzivas vsude normalne indent = 2?

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/RocketClient.swift
>      public let fetchAsync: () async throws -> [Rocket]
Bud konzistentni s namingem... Tady oboje funkce delaji fetchAllRockets... navic jsou obe async. Tak je pojmenuj aspon `fetchAllRocketsAsync` a `fetchAllRocketsCombine` i kdyz to bude porad async funkce. Davej si zalezet na detailech jako je naming, je to ve vysledku dost klicovy.

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Features/Package.swift
> +            targets: ["RocketErrorView"]),
Tady je to spatne zformatovany.

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/ErrorHandlingConcurrency/ErrorAlertState.swift
> +    static func errorAlert(error: Error?) -> AlertState {
Nemel bys mit funkci ktera resi alerty a prijde do ni `Optional` error. To by mela resit ta vrstva nad ni. To neni zodpovednost tyhle funkce.

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/RocketClient.swift
> +  public var fetchAllRocketsCombine: ()  -> AnyPublisher<[Rocket], RocketError>
Nemas tady nahodou 2 whitespaces pred tou `->`?

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketClientTests/RocketClient+happyTests.swift
> +  >! = DispatchQueue.test
Tohle se vejde na jeden radek ne? Jako naformatovany je to spravne ale je to zbytecny to mit na vice radek, kdyz se to vejde na 120 znaku...

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp.xcodeproj/project.pbxproj
> +		F07059422A01B0100076B3D1 /* Resources.xcassets in Resources */ = {isa = PBXBuildFile; fileRef = F07059412A01B0100076B3D1 /* Resources.xcassets */; };
Mas tam nastavenej ten script co automaticky dela ty type-safe veci pomoci swiftgen?

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp.xcodeproj/project.xcworkspace/xcuserdata/martinficek.xcuserdatad/UserInterfaceState.xcuserstate
Proc mas workspace? To vubec nepotrebujes ne?

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/ErrorForAlerts/ErrorAlertState.swift
> +      //            return unimplemented("\(Self.self) is not confronting ErrorHandlingConcurrency")
Co ten zakomentovanej kod? Nechces to dat pryc?

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/ErrorForAlerts/ErrorAlertState.swift
> +public extension AlertState {
Jinak tohle urcite neni target v `Domain` vrstve, ma to bejt ve `Feature` vrstve. Idealne treba `TCAExtensions` target, nebo `ErrorAlerts` nebo tak. Ale je to UI vec, nemuze to bejt v `Domain`.

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/ErrorForAlerts/ErrorForAlerts.swift
> +struct GeneralAsyncError: ErrorForAlerts {
Nevim jestli tenhle error pouzivas, ale nema nic moc nazev...

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/Models/Errors/NetworkError+Alerts.swift
> +extension NetworkError: ModelConvertibleErrorCapable {
K cemu tu mas `NetworkError`? Ten nepotrebujes ne?

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/Models/Errors/RocketError.swift
> +import Foundation
Ten adresar `Errors` bych dal asi na stejnou urovni jako `Models`. Jako je pravda, ze jsou to trochu modely ale taky trochu ne (zalezi na uhlu pohledu) ale tak at zbytecne nevnorujeme...

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/RocketClient+DependencyKey.swift
> +//          .eraseToAnyPublisher()
Tady mas nakej zakomentovanej kod a TODOcka...

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketClientTests/RocketClient+happyTests.swift
> +    let result = try awaitPublisher(sut.fetchAllRocketsCombine())
Hele napsal bych tenhle test normalne reaktivne, at si to pocvicis. Normalne sinknes, disposnes do `Set<AnyCancellable>` a pouzijes treba expectations...

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketClientTests/RocketClient+sadTests.swift
> +  //    override func invokeTest() {
Tady zase nakej zakomentovanej kod...

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketClientTests/RocketClient+sadTests.swift
> +    waitForExpectations(timeout: 10)
Nikdy nedavej ten timeout takhle vysokej!! Pokud ten test bude nekdy failovat, tak se to tady na 10s zasekne. Za me je prijatelny tak 0.1 max!

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Features/Sources/RocketDetail/RocketDetailCore.swift
> +        public var id: String { rocket.id }
Tady to mas nejak divne zformatovany... Ale formatting prijde v druhy vlne co? Kdyztak si to resolvni...

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Features/Sources/RocketErrorView/RocketErrorView.swift
> +public struct RocketErrorView: View {
Mas jeste jeden podobnej target, kterej ma ty extensions pro AlertState. Cili, musis k tomu pristupovat koncepcne. Bud das oboje sem a vytvoris z toho vlastne takovou prepouzitelnou feature, nebo budes mit tuhle cast tady a tamtu cast jinde ale musi to spolu nejak logicky hrat...

2023-05-12 14:20 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Features/Tests/RocketDetailTests/RocketDetailCoreTests.swift
> +//    let rocketPhotosAction = RocketPhotosCore.Action.onAppear
Mas tu ruzne zakomentovanej kod, melo by to bejt spis cisty...

2023-05-12 19:27 UTC, yOoZZyOzzbourne commented on Ficek_QuantiApp/Ficek_QuantiApp/Features/Sources/RocketErrorView/RocketErrorView.swift
> +   public var body: some View {
Ano, opravil jsem to v tom formátování ale bohůžel tam vznikl takový merge conflict že to projedu celé znova

2023-05-12 19:35 UTC, yOoZZyOzzbourne commented on Ficek_QuantiApp/Ficek_QuantiApp.xcodeproj/project.xcworkspace/xcuserdata/martinficek.xcuserdatad/UserInterfaceState.xcuserstate
Ani nevím jak se to tam dostalo

2023-05-12 20:00 UTC, yOoZZyOzzbourne commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/Models/Errors/NetworkError+Alerts.swift
> +extension NetworkError: ModelConvertibleErrorCapable {
je to jen upravené ať mi to háže alerty na každý error pěkně a nemusím mít v Reduceru 150 řádkový switch

2023-05-13 18:54 UTC, troupmar requested changes

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/fastlane/.env.default
> +APP_IDENTIFIER = "com.quanti.swift.NN-mobile-communicator"
Tohle neni asi spravnej naming, to samy dole to APP_NAME atd. Nevim kde ste to vzali, pre sem se koukal do tech templates a tam to neni...

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Infrastructure/Sources/XCTestHelper/XCTestHelper.swift
> +  public func awaitPublisher<T: Publisher>(
Tohle je strasne specificky jmeno targetu. Ja bych to pojmenoval radsi vic obecnejc, treba `TestUtils`.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/Models/RocketMock.swift
Tohle by se melo jmenovat `Rocket+mock`.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/RocketClient+DependencyKey.swift
> +  public static let testValue = RocketClient(
Mel bys mit svoje zvlastni soubory `RocketClient+live`, `RocketClient+test` a `RocketClient+preview`.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Infrastructure/Sources/NetworkClientDependency/NetworkClient+DependencyKey.swift
> +  public static var liveValue: NetworkClient {
Tohle taky rozdelit do samostatnych souboru.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Infrastructure/Sources/CoreMotionClient/CoreMotionClient+DependencyKey.swift
> +  public static var liveValue: CoreMotionClient {
Tady taky rozdelit do samostatnych souboru.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/Models/ModelConverter/RocketConverter.swift
> +  static func live() -> Self {
Rozdeluj fakt vsechny ty instance do samostatnych souboru.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/Models/Rocket.swift
>  public struct Rocket: Equatable, Identifiable {
Bylo by fajn mit asi dva samostatny podaresare, `Data` pro DTO a `Domain` pro domenovy modely.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketConvertersTests/RocketConverter+sadTests.swift
>  final class RocketRonverterSadTests: XCTestCase {
Testy musi 1:1 odpovidat produkcni adresarovy strukture. Takze v RocketClientTests > Converters.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/Models/ModelConverter/DepencendyValues+rocketConverter.swift
> -    public var diameterConverter: DiameterConverter {
Adresar Converters ma bejt na stejny urovni jako Models, ne v nem.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketClientTests/RocketClient+happyTests.swift
> +          XCTAssertNoDifference(rocket, [Rocket].mock)
Tohle neni uplne spravne. Pokud ti prijde prijde jen finished a zadna hodnota, tak ti ten test taky projde a to je false positive. Musis na `receiveValue` assertovat hodnotu (jak to delas) a pak jeste flipnout nejakej boolean, treba `valueReceived` na `true`. Pak po tom `waitForExpectations` jeste assertovat ten boolean. Zaroven se mi nelibi moc jak neprehledne resis to `failure` a `finished`. Pekne si izolovane ohandluj oba cases, na `failure` dej `XCTFail` a na `finished` dej `fulfill`. Nepouzivej to propadavani pres `break` a `continue`.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketClientTests/RocketClient+sadTests.swift
> +            if error.underlyingError is NetworkError {
Tohle muzes podle me dat do `where` klauzule toho `case let .failure`.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketClientTests/RocketClient+happyTests.swift
> +          XCTAssertNoDifference(rocket, [Rocket].mock)
Oprav to pls ve vsech testech.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketClientTests/RocketClient+sadTests.swift
> +      let _ = try await sut.fetchAllRocketsAsync()
Tady na to existuje urcite uz nejakej `XCTThrows` nebo neco takovyho, at tu nemusis delat ten do-catch explicitne.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketConvertersTests/RocketConverter+happyTests.swift
> +    Just(rocket.diameter)
Tady to mas spatne naformatovany. Nikdy neni po `=` nova radka.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketConvertersTests/RocketConverter+happyTests.swift
> +      .convertToDomainModel(using: converter)
Tyhle testy podle me delas uplne zbytecne, zatahujes do toho ten operator `convertToDomainModel`, ten uz je ale otestovanej. Proste si tu udelej instanci toho convertoru a testuj to normalne jako jednoduchou funkco, neni treba tu delat zadny asynchronni veci.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketConvertersTests/RocketConverter+happyTests.swift
> +      .convertToDomainModel(using: converter)
Oprav pls tak vsechny testy na convertory.

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Features/Sources/Resources/Resources.swift
Proc sou tady Resources? K cemu to jako je?

2023-05-13 18:54 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Features/Sources/RocketDetail/RocketDetailCore.swift
> +      RocketLaunchCore()
Jakto, ze tohle existuje vzdycky? Ja myslel, ze se na tuhle feature naviguje, takze ten state musi bejt Optional ne? Prece nemusi existovat vzdycky, uzivatel se na tu scenu nemusi nikdy navigovat. Mel bys tu pouzit Optional state a pouzit `IfLetStore`.

2023-05-13 19:02 UTC, troupmar requested changes

2023-05-13 19:02 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Features/Sources/RocketErrorView/RocketErrorView.swift
> +      Button("Close the app") {
Jako je fajn, ze si dal pryc ten `fatalError` ale ... :D Kdyz tu mas tlacitko, tak musi nejak reagovat a "close the app" asi neni uplne vhodnej nazev. Navic bys mel uzivatele umet nekam navigovat. Pokud ho ted neni zrovna kam navigovat, tak aspon ale to tlacitko bud dej pryc a nebo ho vhodne pojmenuj. Tohle je uzivatelsky hodne nestastny...

2023-05-13 21:56 UTC, yOoZZyOzzbourne commented on Ficek_QuantiApp/Ficek_QuantiApp/Features/Sources/Resources/Resources.swift
Já je tam nemám, mazal jsem to protože to byly moje obrázky které jsem kvůli swiftgenu přesouval do infrastructure

2023-05-19 11:05 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/Models/RocketMock.swift
za `+` se v 90% pripadech dava maly pismeno. Tady ten `Rocket` rozsirujes o instanci, takze o maly pismeno. Neco jinyho je treba `RocketClient+DependencyKey`, protoze tam to rozsirujes o konkretni typ. Kdyz rozsirujes o konkretni typ, tak to das velky, pre nechces samozrejme nabouravat ten nazev, tj. `DependencyKey`. Ale kdyz rozsirujes o neco instancniho nebo obecnejsiho, tak je tam maly pismeno.

2023-05-19 11:25 UTC, troupmar requested changes

2023-05-19 11:25 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/RocketClient+live.swift
> +import Foundation
Kde to pridavas do `DependencyKeys` toho `RocketClient`a?

2023-05-19 11:25 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Sources/RocketClient/ModelConverter/DepencendyValues+rocketConverter.swift
> +import Foundation
Pojmenuj ten adresar prosim `Converters`. Mas tam treba `Models`, taky to nemas jednotnym cislem. Navic to slovo `Model` je tam zbytecny, to je jasny ze `converters` delaji konverze modelu. Premejslej vic nad tou konzistenci.

2023-05-19 11:25 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketConvertersTests/RocketConverter+sadTests.swift
>  final class RocketRonverterSadTests: XCTestCase {
To neodpovida... Prvni je `{TargetName}Tests`, protoze to tak vyzaduje SPM. Pak uz ty nazvy podadresaru musi odpovidat presne produkcnimu kodu. Tady `Converters`.

2023-05-19 11:25 UTC, troupmar commented on Ficek_QuantiApp/Ficek_QuantiApp/Domain/Tests/RocketClientTests/RocketClient+happyTests.swift
> +            valueRecieved = true
Tak 3 veci k tomuhle:
- `expectation.fullfill` musi bejt az podtim `valueReceived`. Co kdyby se ti naplnila dole ta expectation a zacal se vyhodnocovat ten `XCTAssertTrue` driv nez se `valueReceived` preklopi na `true`?
- tohle nema bejt prece tady, zamysli se nadtim. Kdyz ti neprijde zadna `value`, pouze `finished` stav, tak se vyhodnoti ten test jako passing, pritom to neni ocekavany chovani
- mas tam typo: `valueRecieved` -> `valueReceived`

2023-05-19 13:56 UTC, troupmar approved these changes

2023-05-20 12:09 UTC, merged